name: 'Terraform Destroy'

on:
  workflow_dispatch:

permissions: write-all

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set AWS Account ID
      id: account
      run: |
        echo "ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

    - name: Check for existing Terraform state file
      id: check_state
      run: |
        if aws s3api head-object --bucket aigoat-state-files-${{ env.ACCOUNT_ID }} --key terraform.tfstate 2>/dev/null; then
          echo "STATE_EXISTS=true" >> $GITHUB_ENV
        else
          echo "STATE_EXISTS=false" >> $GITHUB_ENV
        fi

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install boto3
      run: pip install boto3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0  # Tu peux ajuster selon la version souhaitée

    - name: Terraform Destroy Operations
      id: destroy
      run: |
        if [[ "$STATE_EXISTS" == "true" ]]; then
          aws s3 cp s3://aigoat-state-files-${{ env.ACCOUNT_ID }}/terraform.tfstate ./terraform.tfstate || true

          terraform init -backend=false  # Désactivation du backend pour éviter les erreurs
          
          terraform destroy -auto-approve -input=false && echo "DESTROY_SUCCESS=true" >> $GITHUB_ENV || echo "DESTROY_SUCCESS=false" >> $GITHUB_ENV
        else
          echo "No state file found. Skipping destroy operation."
          echo "DESTROY_SUCCESS=false" >> $GITHUB_ENV
        fi

    - name: Remove tfstate from S3
      if: env.DESTROY_SUCCESS == 'true'
      run: |
        aws s3 rm s3://aigoat-state-files-${{ env.ACCOUNT_ID }}/terraform.tfstate
